### ISSUE TITLE
Document PSSI tag

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/crate-digger#7]
I want to stop discussing this in #5, it deserves its own issue! 😆 

@mganss I have updated the online [pdf](https://deepsymmetry.org/cratedigger/Analysis.pdf) to include my draft so far, if you would be so kind as to review it. I need to add the table of actual phrase ID interpretations, which I have enough information to do already, but I don’t know for certain things like the value of _len_header_ so I hope you can send me a `PSSI` file to study as well.

**Comment by mganss** [comment]
@brunchboy I've sent you an e-mail with a few example files plus a screenshot.

- `len_header` is 32
- The phrase labels in rekordbox are all caps, i.e. CHORUS etc.
- Missing space at "phrasesare"

The GitHub profile URL is fine.

**Comment by brunchboy** [comment]
Excellent, thanks so much. That’s a surprising value for `len_header` given the diagrams I have sketched out so far, so I greatly appreciate having some actual example tags to study.

**Comment by brunchboy** [comment]
I have had a chance to make those fixes and finish my draft of an explanation. The [PDF](https://deepsymmetry.org/cratedigger/Analysis.pdf) has been updated, and if it looks good to you we can close this issue.

**Comment by mganss** [comment]
Looks good 👍
